- name: Check for rke2-agent
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/rke2-agent.service
  register: rke2_agent

- name: Install rke2 agent
  ansible.builtin.shell:
    cmd: |
      curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -
  when: not rke2_agent.stat.exists

- name: Register token
  ansible.builtin.shell:
    cmd: |
      cat host_files/kubemaster/token
  register: token
  delegate_to: localhost

- name: Create Rancher Config
  ansible.builtin.copy:
    content: |
      server: https://kubemaster.subatomicnetworks.net:9345
      token: "{{token.stdout}}"
    dest: /etc/rancher/rke2/config.yaml
  notify: Restart rke2-agent

- name: Copy Cert
  ansible.builtin.copy:
    src: host_files/kubemaster/snakeoil.pem
    dest: /etc/pki/ca-trust/source/anchors/
  notify: Update CA Trust
