- name: Create Rancher Config
  ansible.builtin.copy:
    content: |
      token: some-shared-secret
      server: https://kubemaster.subatomicnetworks.net:9345
      tls-san:
        - kubemaster
        - kubemaster.subatomicnetworks.net
    dest: /etc/rancher/rke2/config.yaml

- name: Install rke2 agent
  ansible.builtin.shell:
    cmd: |
      curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -
      systemctl enable rke2-agent.service
      systemctl start rke2-agent.service
